server:
  port: 8083
  
zuul:
  host:
      connect-timeout-millis: 10000
      socket-timeout-millis: 10000
  sensitive-headers: 
  routes:
    api-gateway:
      path: /myProduct/**
      service-id: product
      #设置cookies可以传递
      sensitive-headers: 
  #简洁写法
#    product: /myProduct/**
  #排除某些路由
  ignored-patterns:
    - /**/product/listForOrder
management:
  security:
    enabled: false
spring:
  redis:
    host: 192.168.1.146
    port: 6379

ribbon:  
  ReadTimeout: 10000
  ConnectTimeout: 10000
  
hystrix:
    command:
        default:
            execution:
                isolation:
                    thread:
                        timeout-in-milliseconds: 10000
