server:
  port: 8083
  
zuul:
  sensitive-headers: 
  routes:
    api-gateway:
      path: /myProduct/**
      service-id: product
      #设置cookies可以传递
      sensitive-headers: 
  #简洁写法
#    product: /myProduct/**
  #排除某些路由
  ignored-patterns:
    - /**/product/listForOrder
management:
  security:
    enabled: false
spring:
  redis:
    host: 192.168.1.146
    port: 6379
