server:
  port: 8081
spring:
  application:
    name: order
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: root
    url: jdbc:mysql://localhost:3306/SpringCloud_Sell?characterEncoding=utf-8&useSSL=false
    username: root
  rabbitmq:
    host: 192.168.1.146
    port: 5672
    username: guest
    password: guest  
  jpa:
    show-sql: true
  profiles:
    active: dev  
