server:
  port: 8084
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: root
    url: jdbc:mysql://localhost:3306/SpringCloud_Sell?characterEncoding=utf-8&useSSL=false
    username: root
  jpa:
    show-sql: true
#   rabbitmq:
#     host: 192.168.1.146
#     password: guest
#     port: 5672
#     username: guest
  redis:
    host: 192.168.1.153
    port: 6379
